/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * CAPEF Digital Enrollment API
 * OpenAPI spec version: 0.1.0
 */
/**
 * @nullable
 */
export type PhysiqueDataSexe = typeof PhysiqueDataSexe[keyof typeof PhysiqueDataSexe] | null;
export declare const PhysiqueDataSexe: {
    readonly M: "M";
    readonly F: "F";
};
//# sourceMappingURL=physiqueDataSexe.d.ts.map